# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu-precise-64bit"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.hostname = "vagrant.delorean.com"

  
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :private_network, ip: "192.168.33.10"
  
  config.vm.synced_folder "../../delorean", "/webapps/delorean"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", path: "dns-reroute.sh"
  #config.vm.provision "shell", inline: "apt-get update"
  
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file  = "init.pp"
    puppet.module_path = "../puppet/modules"
  end

end
